# Generated by Django 4.2.2 on 2023-06-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('AdmissionionID', models.IntegerField(primary_key=True, serialize=False)),
                ('AdmissionDate', models.DateField()),
                ('Name', models.CharField(max_length=100)),
                ('DataOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
